# Generated by Django 6.0 on 2026-06-29 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tooo',
            old_name='User',
            new_name='user',
        ),
    ]
